### ISSUE TITLE
Add Support for Laravel 5.1

### ISSUE THREAD

**Issue by kamilersz** [nurmanhabib/navigator#1]
Project composer cannot be updated because this library depends on illuminate/support: 5.0.\* package

**Comment by nurmanhabib** [comment]
well i will update to support Laravel 5.1

**Comment by kamilersz** [comment]
Great, thanks

**Comment by nurmanhabib** [comment]
Fix on 3.1.0

https://github.com/nurmanhabib/navigator/tree/3.1.0
